package SuperSwing.Componente.DatePicker;

import javax.swing.JButton;

/**
 *
 * @author rafael.albuquerque
 */
public class Anos extends javax.swing.JPanel {
    
    private Evento evento;
    private int anoInicial;
    
    /**
     * Creates new form Anos
     */
    public Anos() {
        initComponents();
    }

    public int mostrarAno(int ano) {
        ano = calcularAno(ano);
        for (int i = 0; i < getComponentCount(); i++) {
            JButton cmd = (JButton) getComponent(i);
            cmd.setText(ano + "");
            ano++;
        }
        return anoInicial;
    }

    private int calcularAno(int ano) {
        ano -= ano % 10;
        anoInicial = ano;
        return ano;
    }

    private void addEvent() {
        for (int i = 0; i < getComponentCount(); i++) {
            ((Botao) getComponent(i)).setEvent(evento);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmd1 = new SuperSwing.Componente.DatePicker.Botao();
        cmd2 = new SuperSwing.Componente.DatePicker.Botao();
        cmd3 = new SuperSwing.Componente.DatePicker.Botao();
        cmd4 = new SuperSwing.Componente.DatePicker.Botao();
        cmd5 = new SuperSwing.Componente.DatePicker.Botao();
        cmd6 = new SuperSwing.Componente.DatePicker.Botao();
        cmd7 = new SuperSwing.Componente.DatePicker.Botao();
        cmd8 = new SuperSwing.Componente.DatePicker.Botao();
        cmd9 = new SuperSwing.Componente.DatePicker.Botao();
        cmd10 = new SuperSwing.Componente.DatePicker.Botao();
        cmd11 = new SuperSwing.Componente.DatePicker.Botao();
        cmd12 = new SuperSwing.Componente.DatePicker.Botao();
        cmd13 = new SuperSwing.Componente.DatePicker.Botao();
        cmd14 = new SuperSwing.Componente.DatePicker.Botao();
        cmd15 = new SuperSwing.Componente.DatePicker.Botao();
        cmd16 = new SuperSwing.Componente.DatePicker.Botao();
        cmd17 = new SuperSwing.Componente.DatePicker.Botao();
        cmd18 = new SuperSwing.Componente.DatePicker.Botao();
        cmd19 = new SuperSwing.Componente.DatePicker.Botao();
        cmd20 = new SuperSwing.Componente.DatePicker.Botao();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(96, 80));
        setPreferredSize(new java.awt.Dimension(96, 80));
        setLayout(new java.awt.GridLayout(5, 4));

        cmd1.setForeground(new java.awt.Color(75, 75, 75));
        cmd1.setText("2018");
        cmd1.setName("ano"); // NOI18N
        cmd1.setOpaque(true);
        add(cmd1);

        cmd2.setForeground(new java.awt.Color(75, 75, 75));
        cmd2.setText("2019");
        cmd2.setName("ano"); // NOI18N
        cmd2.setOpaque(true);
        add(cmd2);

        cmd3.setForeground(new java.awt.Color(75, 75, 75));
        cmd3.setText("2020");
        cmd3.setName("ano"); // NOI18N
        cmd3.setOpaque(true);
        add(cmd3);

        cmd4.setForeground(new java.awt.Color(75, 75, 75));
        cmd4.setText("2021");
        cmd4.setName("ano"); // NOI18N
        cmd4.setOpaque(true);
        add(cmd4);

        cmd5.setForeground(new java.awt.Color(75, 75, 75));
        cmd5.setText("2022");
        cmd5.setName("ano"); // NOI18N
        cmd5.setOpaque(true);
        add(cmd5);

        cmd6.setForeground(new java.awt.Color(75, 75, 75));
        cmd6.setText("2023");
        cmd6.setName("ano"); // NOI18N
        cmd6.setOpaque(true);
        add(cmd6);

        cmd7.setForeground(new java.awt.Color(75, 75, 75));
        cmd7.setText("2024");
        cmd7.setName("ano"); // NOI18N
        cmd7.setOpaque(true);
        add(cmd7);

        cmd8.setForeground(new java.awt.Color(75, 75, 75));
        cmd8.setText("2025");
        cmd8.setName("ano"); // NOI18N
        cmd8.setOpaque(true);
        add(cmd8);

        cmd9.setForeground(new java.awt.Color(75, 75, 75));
        cmd9.setText("2026");
        cmd9.setName("ano"); // NOI18N
        cmd9.setOpaque(true);
        add(cmd9);

        cmd10.setForeground(new java.awt.Color(75, 75, 75));
        cmd10.setText("2027");
        cmd10.setName("ano"); // NOI18N
        cmd10.setOpaque(true);
        add(cmd10);

        cmd11.setForeground(new java.awt.Color(75, 75, 75));
        cmd11.setText("2028");
        cmd11.setName("ano"); // NOI18N
        cmd11.setOpaque(true);
        add(cmd11);

        cmd12.setForeground(new java.awt.Color(75, 75, 75));
        cmd12.setText("2029");
        cmd12.setName("ano"); // NOI18N
        cmd12.setOpaque(true);
        add(cmd12);

        cmd13.setForeground(new java.awt.Color(75, 75, 75));
        cmd13.setText("2030");
        cmd13.setName("ano"); // NOI18N
        cmd13.setOpaque(true);
        add(cmd13);

        cmd14.setForeground(new java.awt.Color(75, 75, 75));
        cmd14.setText("2031");
        cmd14.setName("ano"); // NOI18N
        cmd14.setOpaque(true);
        add(cmd14);

        cmd15.setForeground(new java.awt.Color(75, 75, 75));
        cmd15.setText("2032");
        cmd15.setName("ano"); // NOI18N
        cmd15.setOpaque(true);
        add(cmd15);

        cmd16.setForeground(new java.awt.Color(75, 75, 75));
        cmd16.setText("2033");
        cmd16.setName("ano"); // NOI18N
        cmd16.setOpaque(true);
        add(cmd16);

        cmd17.setForeground(new java.awt.Color(75, 75, 75));
        cmd17.setText("2034");
        cmd17.setName("ano"); // NOI18N
        cmd17.setOpaque(true);
        add(cmd17);

        cmd18.setForeground(new java.awt.Color(75, 75, 75));
        cmd18.setText("2035");
        cmd18.setName("ano"); // NOI18N
        cmd18.setOpaque(true);
        add(cmd18);

        cmd19.setForeground(new java.awt.Color(75, 75, 75));
        cmd19.setText("2036");
        cmd19.setName("ano"); // NOI18N
        cmd19.setOpaque(true);
        add(cmd19);

        cmd20.setForeground(new java.awt.Color(75, 75, 75));
        cmd20.setText("2037");
        cmd20.setName("ano"); // NOI18N
        cmd20.setOpaque(true);
        add(cmd20);
    }// </editor-fold>//GEN-END:initComponents

    public Evento getEvent() {
        return evento;
    }

    public void setEvent(Evento evento) {
        this.evento = evento;
        addEvent();
    }

    public int proximo(int ano) {
        mostrarAno(ano + 20);
        return anoInicial;
    }

    public int anterior(int ano) {
        mostrarAno(ano - 20);
        return anoInicial;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private SuperSwing.Componente.DatePicker.Botao cmd1;
    private SuperSwing.Componente.DatePicker.Botao cmd10;
    private SuperSwing.Componente.DatePicker.Botao cmd11;
    private SuperSwing.Componente.DatePicker.Botao cmd12;
    private SuperSwing.Componente.DatePicker.Botao cmd13;
    private SuperSwing.Componente.DatePicker.Botao cmd14;
    private SuperSwing.Componente.DatePicker.Botao cmd15;
    private SuperSwing.Componente.DatePicker.Botao cmd16;
    private SuperSwing.Componente.DatePicker.Botao cmd17;
    private SuperSwing.Componente.DatePicker.Botao cmd18;
    private SuperSwing.Componente.DatePicker.Botao cmd19;
    private SuperSwing.Componente.DatePicker.Botao cmd2;
    private SuperSwing.Componente.DatePicker.Botao cmd20;
    private SuperSwing.Componente.DatePicker.Botao cmd3;
    private SuperSwing.Componente.DatePicker.Botao cmd4;
    private SuperSwing.Componente.DatePicker.Botao cmd5;
    private SuperSwing.Componente.DatePicker.Botao cmd6;
    private SuperSwing.Componente.DatePicker.Botao cmd7;
    private SuperSwing.Componente.DatePicker.Botao cmd8;
    private SuperSwing.Componente.DatePicker.Botao cmd9;
    // End of variables declaration//GEN-END:variables
}
