package SuperSwing.Componente.DatePicker;

import java.awt.Color;
import java.time.LocalDate;
import java.util.Calendar;
import javax.swing.JButton;

/**
 *
 * @author rafael.albuquerque
 */
public class Datas extends javax.swing.JPanel {
    
    private Evento evento;
    private final int MES;
    private final int ANO;
    private final int DIA;
    private int mes;
    private int ano;
    private int diaSelecionado = 0;
    private int dataInicial;
    private int dias_mes;

    /**
     * Creates new form Datas
     */
    public Datas() {
        initComponents();
        LocalDate date = LocalDate.now();
        DIA = date.getDayOfMonth();
        MES = date.getMonthValue();
        ANO = date.getYear();
    }
    
    public void mostrarData(int mes, int ano, DataSelecionada dataSelecionada) {
        this.mes = mes;
        this.ano = ano;
        // diaSelecionado = 0;
        Calendar cd = Calendar.getInstance();
        cd.set(ano, mes - 1, 1);
        int inicio = cd.get(Calendar.DAY_OF_WEEK);
        dias_mes = cd.getActualMaximum(Calendar.DAY_OF_MONTH);
        if (inicio == 1) {
            inicio += 7;
        }
        clear();
        inicio += 5;
        dataInicial = inicio;
        for (int i = 1; i <= dias_mes; i++) {
            Botao cmd = (Botao) getComponent(inicio);
            cmd.setCor(getForeground());
            cmd.setText(String.valueOf(i));
            if (i == DIA && mes == MES && ano == ANO) {
                cmd.setBackground(new Color(224, 214, 229));
            } else {
                cmd.setBackground(Color.WHITE);
            }
            if (i == dataSelecionada.getDia() && mes == dataSelecionada.getMes() && ano == dataSelecionada.getAno()) {
                cmd.setBackground(getForeground());
                cmd.setForeground(new Color(255, 255, 255));
            }
            inicio++;
        }
    }

    private void clear() {
        for (int i = 7; i < getComponentCount(); i++) {
            ((JButton) getComponent(i)).setText("");
        }
    }

    public void limparSelecao() {
        for (int i = 7; i < getComponentCount(); i++) {
            JButton cmd = (JButton) getComponent(i);
            if (MES == mes && ano == ANO && !cmd.getText().equals("") && Integer.parseInt(cmd.getText()) == DIA) {
                cmd.setBackground(new Color(224, 214, 229));
                cmd.setForeground(new java.awt.Color(75, 75, 75));
            } else {
                cmd.setBackground(Color.WHITE);
                cmd.setForeground(new java.awt.Color(75, 75, 75));
            }
        }
        diaSelecionado = 0;
    }

    private void addEvent() {
        for (int i = 7; i < getComponentCount(); i++) {
            ((Botao) getComponent(i)).setEvent(evento);
        }
    }

    public void setDiaSelecionado(int index) {
        diaSelecionado = index;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seg = new SuperSwing.Componente.DatePicker.Botao();
        ter = new SuperSwing.Componente.DatePicker.Botao();
        qua = new SuperSwing.Componente.DatePicker.Botao();
        qui = new SuperSwing.Componente.DatePicker.Botao();
        sex = new SuperSwing.Componente.DatePicker.Botao();
        sab = new SuperSwing.Componente.DatePicker.Botao();
        dom = new SuperSwing.Componente.DatePicker.Botao();
        cmd1 = new SuperSwing.Componente.DatePicker.Botao();
        cmd43 = new SuperSwing.Componente.DatePicker.Botao();
        cmd44 = new SuperSwing.Componente.DatePicker.Botao();
        cmd45 = new SuperSwing.Componente.DatePicker.Botao();
        cmd46 = new SuperSwing.Componente.DatePicker.Botao();
        cmd47 = new SuperSwing.Componente.DatePicker.Botao();
        cmd48 = new SuperSwing.Componente.DatePicker.Botao();
        cmd49 = new SuperSwing.Componente.DatePicker.Botao();
        cmd50 = new SuperSwing.Componente.DatePicker.Botao();
        cmd51 = new SuperSwing.Componente.DatePicker.Botao();
        cmd52 = new SuperSwing.Componente.DatePicker.Botao();
        cmd53 = new SuperSwing.Componente.DatePicker.Botao();
        cmd54 = new SuperSwing.Componente.DatePicker.Botao();
        cmd55 = new SuperSwing.Componente.DatePicker.Botao();
        cmd56 = new SuperSwing.Componente.DatePicker.Botao();
        cmd57 = new SuperSwing.Componente.DatePicker.Botao();
        cmd58 = new SuperSwing.Componente.DatePicker.Botao();
        cmd59 = new SuperSwing.Componente.DatePicker.Botao();
        cmd60 = new SuperSwing.Componente.DatePicker.Botao();
        cmd61 = new SuperSwing.Componente.DatePicker.Botao();
        cmd62 = new SuperSwing.Componente.DatePicker.Botao();
        cmd63 = new SuperSwing.Componente.DatePicker.Botao();
        cmd64 = new SuperSwing.Componente.DatePicker.Botao();
        cmd65 = new SuperSwing.Componente.DatePicker.Botao();
        cmd66 = new SuperSwing.Componente.DatePicker.Botao();
        cmd67 = new SuperSwing.Componente.DatePicker.Botao();
        cmd68 = new SuperSwing.Componente.DatePicker.Botao();
        cmd69 = new SuperSwing.Componente.DatePicker.Botao();
        cmd70 = new SuperSwing.Componente.DatePicker.Botao();
        cmd71 = new SuperSwing.Componente.DatePicker.Botao();
        cmd72 = new SuperSwing.Componente.DatePicker.Botao();
        cmd73 = new SuperSwing.Componente.DatePicker.Botao();
        cmd74 = new SuperSwing.Componente.DatePicker.Botao();
        cmd75 = new SuperSwing.Componente.DatePicker.Botao();
        cmd76 = new SuperSwing.Componente.DatePicker.Botao();
        cmd77 = new SuperSwing.Componente.DatePicker.Botao();
        cmd78 = new SuperSwing.Componente.DatePicker.Botao();
        cmd79 = new SuperSwing.Componente.DatePicker.Botao();
        cmd80 = new SuperSwing.Componente.DatePicker.Botao();
        cmd81 = new SuperSwing.Componente.DatePicker.Botao();
        cmd82 = new SuperSwing.Componente.DatePicker.Botao();
        cmd83 = new SuperSwing.Componente.DatePicker.Botao();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(140, 154));
        setPreferredSize(new java.awt.Dimension(140, 154));
        setLayout(new java.awt.GridLayout(7, 7));

        seg.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 5, 1));
        seg.setForeground(new java.awt.Color(118, 118, 118));
        seg.setText("Seg");
        seg.setMaximumSize(new java.awt.Dimension(20, 22));
        seg.setMinimumSize(new java.awt.Dimension(20, 22));
        seg.setPreferredSize(new java.awt.Dimension(20, 22));
        add(seg);

        ter.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 5, 1));
        ter.setForeground(new java.awt.Color(118, 118, 118));
        ter.setText("Ter");
        ter.setMaximumSize(new java.awt.Dimension(20, 22));
        ter.setMinimumSize(new java.awt.Dimension(20, 22));
        ter.setPreferredSize(new java.awt.Dimension(20, 22));
        add(ter);

        qua.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 5, 1));
        qua.setForeground(new java.awt.Color(118, 118, 118));
        qua.setText("Qua");
        qua.setMaximumSize(new java.awt.Dimension(20, 22));
        qua.setMinimumSize(new java.awt.Dimension(20, 22));
        qua.setPreferredSize(new java.awt.Dimension(20, 22));
        add(qua);

        qui.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 5, 1));
        qui.setForeground(new java.awt.Color(118, 118, 118));
        qui.setText("Qui");
        qui.setMaximumSize(new java.awt.Dimension(20, 22));
        qui.setMinimumSize(new java.awt.Dimension(20, 22));
        qui.setPreferredSize(new java.awt.Dimension(20, 22));
        add(qui);

        sex.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 5, 1));
        sex.setForeground(new java.awt.Color(118, 118, 118));
        sex.setText("Sex");
        sex.setMaximumSize(new java.awt.Dimension(20, 22));
        sex.setMinimumSize(new java.awt.Dimension(20, 22));
        sex.setPreferredSize(new java.awt.Dimension(20, 22));
        add(sex);

        sab.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 5, 1));
        sab.setForeground(new java.awt.Color(118, 118, 118));
        sab.setText("Sab");
        sab.setMaximumSize(new java.awt.Dimension(20, 22));
        sab.setMinimumSize(new java.awt.Dimension(20, 22));
        sab.setPreferredSize(new java.awt.Dimension(20, 22));
        add(sab);

        dom.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 5, 1));
        dom.setForeground(new java.awt.Color(255, 1, 1));
        dom.setText("Dom");
        dom.setMaximumSize(new java.awt.Dimension(20, 22));
        dom.setMinimumSize(new java.awt.Dimension(20, 22));
        dom.setPreferredSize(new java.awt.Dimension(20, 22));
        add(dom);

        cmd1.setForeground(new java.awt.Color(75, 75, 75));
        cmd1.setMaximumSize(new java.awt.Dimension(0, 0));
        cmd1.setMinimumSize(new java.awt.Dimension(0, 0));
        cmd1.setName("dia"); // NOI18N
        cmd1.setPreferredSize(new java.awt.Dimension(0, 0));
        add(cmd1);

        cmd43.setForeground(new java.awt.Color(75, 75, 75));
        cmd43.setName("dia"); // NOI18N
        add(cmd43);

        cmd44.setForeground(new java.awt.Color(75, 75, 75));
        cmd44.setText("1");
        cmd44.setName("dia"); // NOI18N
        add(cmd44);

        cmd45.setForeground(new java.awt.Color(75, 75, 75));
        cmd45.setText("2");
        cmd45.setName("dia"); // NOI18N
        add(cmd45);

        cmd46.setForeground(new java.awt.Color(75, 75, 75));
        cmd46.setText("3");
        cmd46.setName("dia"); // NOI18N
        add(cmd46);

        cmd47.setForeground(new java.awt.Color(75, 75, 75));
        cmd47.setText("4");
        cmd47.setName("dia"); // NOI18N
        add(cmd47);

        cmd48.setForeground(new java.awt.Color(75, 75, 75));
        cmd48.setText("5");
        cmd48.setName("dia"); // NOI18N
        add(cmd48);

        cmd49.setForeground(new java.awt.Color(75, 75, 75));
        cmd49.setText("6");
        cmd49.setName("dia"); // NOI18N
        add(cmd49);

        cmd50.setForeground(new java.awt.Color(75, 75, 75));
        cmd50.setText("7");
        cmd50.setName("dia"); // NOI18N
        add(cmd50);

        cmd51.setForeground(new java.awt.Color(75, 75, 75));
        cmd51.setText("8");
        cmd51.setName("dia"); // NOI18N
        add(cmd51);

        cmd52.setForeground(new java.awt.Color(75, 75, 75));
        cmd52.setText("9");
        cmd52.setName("dia"); // NOI18N
        add(cmd52);

        cmd53.setForeground(new java.awt.Color(75, 75, 75));
        cmd53.setText("10");
        cmd53.setName("dia"); // NOI18N
        add(cmd53);

        cmd54.setForeground(new java.awt.Color(75, 75, 75));
        cmd54.setText("11");
        cmd54.setName("dia"); // NOI18N
        add(cmd54);

        cmd55.setForeground(new java.awt.Color(75, 75, 75));
        cmd55.setText("12");
        cmd55.setName("dia"); // NOI18N
        add(cmd55);

        cmd56.setForeground(new java.awt.Color(75, 75, 75));
        cmd56.setText("13");
        cmd56.setName("dia"); // NOI18N
        add(cmd56);

        cmd57.setForeground(new java.awt.Color(75, 75, 75));
        cmd57.setText("14");
        cmd57.setName("dia"); // NOI18N
        add(cmd57);

        cmd58.setForeground(new java.awt.Color(75, 75, 75));
        cmd58.setText("15");
        cmd58.setName("dia"); // NOI18N
        add(cmd58);

        cmd59.setForeground(new java.awt.Color(75, 75, 75));
        cmd59.setText("16");
        cmd59.setName("dia"); // NOI18N
        add(cmd59);

        cmd60.setForeground(new java.awt.Color(75, 75, 75));
        cmd60.setText("17");
        cmd60.setName("dia"); // NOI18N
        add(cmd60);

        cmd61.setForeground(new java.awt.Color(75, 75, 75));
        cmd61.setText("18");
        cmd61.setName("dia"); // NOI18N
        add(cmd61);

        cmd62.setForeground(new java.awt.Color(75, 75, 75));
        cmd62.setText("19");
        cmd62.setName("dia"); // NOI18N
        add(cmd62);

        cmd63.setForeground(new java.awt.Color(75, 75, 75));
        cmd63.setText("20");
        cmd63.setName("dia"); // NOI18N
        add(cmd63);

        cmd64.setForeground(new java.awt.Color(75, 75, 75));
        cmd64.setText("21");
        cmd64.setName("dia"); // NOI18N
        add(cmd64);

        cmd65.setForeground(new java.awt.Color(75, 75, 75));
        cmd65.setText("22");
        cmd65.setName("dia"); // NOI18N
        add(cmd65);

        cmd66.setForeground(new java.awt.Color(75, 75, 75));
        cmd66.setText("23");
        cmd66.setName("dia"); // NOI18N
        add(cmd66);

        cmd67.setForeground(new java.awt.Color(75, 75, 75));
        cmd67.setText("24");
        cmd67.setName("dia"); // NOI18N
        add(cmd67);

        cmd68.setForeground(new java.awt.Color(75, 75, 75));
        cmd68.setText("25");
        cmd68.setName("dia"); // NOI18N
        add(cmd68);

        cmd69.setForeground(new java.awt.Color(75, 75, 75));
        cmd69.setText("26");
        cmd69.setName("dia"); // NOI18N
        add(cmd69);

        cmd70.setForeground(new java.awt.Color(75, 75, 75));
        cmd70.setText("27");
        cmd70.setName("dia"); // NOI18N
        add(cmd70);

        cmd71.setForeground(new java.awt.Color(75, 75, 75));
        cmd71.setText("28");
        cmd71.setName("dia"); // NOI18N
        add(cmd71);

        cmd72.setForeground(new java.awt.Color(75, 75, 75));
        cmd72.setText("29");
        cmd72.setName("dia"); // NOI18N
        add(cmd72);

        cmd73.setForeground(new java.awt.Color(75, 75, 75));
        cmd73.setText("30");
        cmd73.setName("dia"); // NOI18N
        add(cmd73);

        cmd74.setForeground(new java.awt.Color(75, 75, 75));
        cmd74.setText("31");
        cmd74.setName("dia"); // NOI18N
        add(cmd74);

        cmd75.setForeground(new java.awt.Color(75, 75, 75));
        cmd75.setName("dia"); // NOI18N
        add(cmd75);

        cmd76.setForeground(new java.awt.Color(75, 75, 75));
        cmd76.setName("dia"); // NOI18N
        add(cmd76);

        cmd77.setForeground(new java.awt.Color(75, 75, 75));
        cmd77.setName("dia"); // NOI18N
        add(cmd77);

        cmd78.setForeground(new java.awt.Color(75, 75, 75));
        cmd78.setName("dia"); // NOI18N
        add(cmd78);

        cmd79.setForeground(new java.awt.Color(75, 75, 75));
        cmd79.setName("dia"); // NOI18N
        add(cmd79);

        cmd80.setForeground(new java.awt.Color(75, 75, 75));
        cmd80.setName("dia"); // NOI18N
        add(cmd80);

        cmd81.setForeground(new java.awt.Color(75, 75, 75));
        cmd81.setName("dia"); // NOI18N
        add(cmd81);

        cmd82.setForeground(new java.awt.Color(75, 75, 75));
        cmd82.setName("dia"); // NOI18N
        add(cmd82);

        cmd83.setForeground(new java.awt.Color(75, 75, 75));
        cmd83.setName("dia"); // NOI18N
        add(cmd83);
    }// </editor-fold>//GEN-END:initComponents

    public Evento getEvent() {
        return evento;
    }

    public void setEvent(Evento evento) {
        this.evento = evento;
        addEvent();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private SuperSwing.Componente.DatePicker.Botao cmd1;
    private SuperSwing.Componente.DatePicker.Botao cmd43;
    private SuperSwing.Componente.DatePicker.Botao cmd44;
    private SuperSwing.Componente.DatePicker.Botao cmd45;
    private SuperSwing.Componente.DatePicker.Botao cmd46;
    private SuperSwing.Componente.DatePicker.Botao cmd47;
    private SuperSwing.Componente.DatePicker.Botao cmd48;
    private SuperSwing.Componente.DatePicker.Botao cmd49;
    private SuperSwing.Componente.DatePicker.Botao cmd50;
    private SuperSwing.Componente.DatePicker.Botao cmd51;
    private SuperSwing.Componente.DatePicker.Botao cmd52;
    private SuperSwing.Componente.DatePicker.Botao cmd53;
    private SuperSwing.Componente.DatePicker.Botao cmd54;
    private SuperSwing.Componente.DatePicker.Botao cmd55;
    private SuperSwing.Componente.DatePicker.Botao cmd56;
    private SuperSwing.Componente.DatePicker.Botao cmd57;
    private SuperSwing.Componente.DatePicker.Botao cmd58;
    private SuperSwing.Componente.DatePicker.Botao cmd59;
    private SuperSwing.Componente.DatePicker.Botao cmd60;
    private SuperSwing.Componente.DatePicker.Botao cmd61;
    private SuperSwing.Componente.DatePicker.Botao cmd62;
    private SuperSwing.Componente.DatePicker.Botao cmd63;
    private SuperSwing.Componente.DatePicker.Botao cmd64;
    private SuperSwing.Componente.DatePicker.Botao cmd65;
    private SuperSwing.Componente.DatePicker.Botao cmd66;
    private SuperSwing.Componente.DatePicker.Botao cmd67;
    private SuperSwing.Componente.DatePicker.Botao cmd68;
    private SuperSwing.Componente.DatePicker.Botao cmd69;
    private SuperSwing.Componente.DatePicker.Botao cmd70;
    private SuperSwing.Componente.DatePicker.Botao cmd71;
    private SuperSwing.Componente.DatePicker.Botao cmd72;
    private SuperSwing.Componente.DatePicker.Botao cmd73;
    private SuperSwing.Componente.DatePicker.Botao cmd74;
    private SuperSwing.Componente.DatePicker.Botao cmd75;
    private SuperSwing.Componente.DatePicker.Botao cmd76;
    private SuperSwing.Componente.DatePicker.Botao cmd77;
    private SuperSwing.Componente.DatePicker.Botao cmd78;
    private SuperSwing.Componente.DatePicker.Botao cmd79;
    private SuperSwing.Componente.DatePicker.Botao cmd80;
    private SuperSwing.Componente.DatePicker.Botao cmd81;
    private SuperSwing.Componente.DatePicker.Botao cmd82;
    private SuperSwing.Componente.DatePicker.Botao cmd83;
    private SuperSwing.Componente.DatePicker.Botao dom;
    private SuperSwing.Componente.DatePicker.Botao qua;
    private SuperSwing.Componente.DatePicker.Botao qui;
    private SuperSwing.Componente.DatePicker.Botao sab;
    private SuperSwing.Componente.DatePicker.Botao seg;
    private SuperSwing.Componente.DatePicker.Botao sex;
    private SuperSwing.Componente.DatePicker.Botao ter;
    // End of variables declaration//GEN-END:variables

    public void proximo() {
        if (diaSelecionado == dias_mes) {
            diaSelecionado = 0;
        }
        JButton cmd = (JButton) getComponent(dataInicial - 1 + diaSelecionado + 1);
        String n = cmd.getText();
        if (!n.equals("") && Integer.parseInt(n) <= dias_mes) {
            diaSelecionado++;
            evento.executar(null, diaSelecionado);
            cmd.setBackground(new Color(206, 110, 245));
        }
    }

    public void anterior() {
        if (diaSelecionado <= 1) {
            diaSelecionado = dias_mes + 1;
        }
        JButton cmd = (JButton) getComponent(dataInicial - 1 + diaSelecionado - 1);
        String n = cmd.getText();
        if (!n.equals("") && cmd.getName() != null) {
            diaSelecionado--;
            evento.executar(null, diaSelecionado);
            cmd.setBackground(new Color(206, 110, 245));
        }
    }

    public void cima() {
        JButton cmd = (JButton) getComponent(dataInicial - 1 + diaSelecionado - 7);
        String n = cmd.getText();
        if (!n.equals("") && cmd.getName() != null) {
            diaSelecionado -= 7;
            evento.executar(null, diaSelecionado);
            cmd.setBackground(new Color(206, 110, 245));
        }
    }

    public void baixo() {
        if (getComponents().length > dataInicial - 1 + diaSelecionado + 7) {
            JButton cmd = (JButton) getComponent(dataInicial - 1 + diaSelecionado + 7);
            String n = cmd.getText();
            if (!n.equals("") && cmd.getName() != null) {
                diaSelecionado += 7;
                evento.executar(null, diaSelecionado);
                cmd.setBackground(new Color(206, 110, 245));
            }
        }
    }

}
