package SuperSwing.Componente.DatePicker;

/**
 *
 * @author rafael.albuquerque
 */
public class Meses extends javax.swing.JPanel {
    
    private Evento evento;

    /**
     * Creates new form Meses
     */
    public Meses() {
        initComponents();
    }
    
    private void addEvento() {
        for (int i = 0; i < getComponentCount(); i++) {
            ((Botao) getComponent(i)).setEvent(evento);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        janeiro = new SuperSwing.Componente.DatePicker.Botao();
        fevereiro = new SuperSwing.Componente.DatePicker.Botao();
        marco = new SuperSwing.Componente.DatePicker.Botao();
        abril = new SuperSwing.Componente.DatePicker.Botao();
        maio = new SuperSwing.Componente.DatePicker.Botao();
        junho = new SuperSwing.Componente.DatePicker.Botao();
        julho = new SuperSwing.Componente.DatePicker.Botao();
        agosto = new SuperSwing.Componente.DatePicker.Botao();
        setembro = new SuperSwing.Componente.DatePicker.Botao();
        outubro = new SuperSwing.Componente.DatePicker.Botao();
        novembro = new SuperSwing.Componente.DatePicker.Botao();
        dezembro = new SuperSwing.Componente.DatePicker.Botao();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(171, 64));
        setPreferredSize(new java.awt.Dimension(171, 64));
        setLayout(new java.awt.GridLayout(4, 4));

        janeiro.setForeground(new java.awt.Color(75, 75, 75));
        janeiro.setText("Janeiro");
        janeiro.setMaximumSize(new java.awt.Dimension(40, 16));
        janeiro.setMinimumSize(new java.awt.Dimension(40, 16));
        janeiro.setName("1"); // NOI18N
        janeiro.setOpaque(true);
        janeiro.setPreferredSize(new java.awt.Dimension(40, 16));
        add(janeiro);

        fevereiro.setForeground(new java.awt.Color(75, 75, 75));
        fevereiro.setText("Fevereiro");
        fevereiro.setMaximumSize(new java.awt.Dimension(40, 16));
        fevereiro.setMinimumSize(new java.awt.Dimension(40, 16));
        fevereiro.setName("2"); // NOI18N
        fevereiro.setOpaque(true);
        fevereiro.setPreferredSize(new java.awt.Dimension(40, 16));
        add(fevereiro);

        marco.setForeground(new java.awt.Color(75, 75, 75));
        marco.setText("Março");
        marco.setMaximumSize(new java.awt.Dimension(40, 16));
        marco.setMinimumSize(new java.awt.Dimension(40, 16));
        marco.setName("3"); // NOI18N
        marco.setOpaque(true);
        marco.setPreferredSize(new java.awt.Dimension(40, 16));
        add(marco);

        abril.setForeground(new java.awt.Color(75, 75, 75));
        abril.setText("Abril");
        abril.setMaximumSize(new java.awt.Dimension(40, 16));
        abril.setMinimumSize(new java.awt.Dimension(40, 16));
        abril.setName("4"); // NOI18N
        abril.setOpaque(true);
        abril.setPreferredSize(new java.awt.Dimension(40, 16));
        add(abril);

        maio.setForeground(new java.awt.Color(75, 75, 75));
        maio.setText("Maio");
        maio.setMaximumSize(new java.awt.Dimension(40, 16));
        maio.setMinimumSize(new java.awt.Dimension(40, 16));
        maio.setName("5"); // NOI18N
        maio.setOpaque(true);
        maio.setPreferredSize(new java.awt.Dimension(40, 16));
        add(maio);

        junho.setForeground(new java.awt.Color(75, 75, 75));
        junho.setText("Junho");
        junho.setMaximumSize(new java.awt.Dimension(40, 16));
        junho.setMinimumSize(new java.awt.Dimension(40, 16));
        junho.setName("6"); // NOI18N
        junho.setOpaque(true);
        junho.setPreferredSize(new java.awt.Dimension(40, 16));
        add(junho);

        julho.setForeground(new java.awt.Color(75, 75, 75));
        julho.setText("Julho");
        julho.setMaximumSize(new java.awt.Dimension(40, 16));
        julho.setMinimumSize(new java.awt.Dimension(40, 16));
        julho.setName("7"); // NOI18N
        julho.setOpaque(true);
        julho.setPreferredSize(new java.awt.Dimension(40, 16));
        add(julho);

        agosto.setForeground(new java.awt.Color(75, 75, 75));
        agosto.setText("Agosto");
        agosto.setMaximumSize(new java.awt.Dimension(40, 16));
        agosto.setMinimumSize(new java.awt.Dimension(40, 16));
        agosto.setName("8"); // NOI18N
        agosto.setOpaque(true);
        agosto.setPreferredSize(new java.awt.Dimension(40, 16));
        add(agosto);

        setembro.setForeground(new java.awt.Color(75, 75, 75));
        setembro.setText("Setembro");
        setembro.setMaximumSize(new java.awt.Dimension(40, 16));
        setembro.setMinimumSize(new java.awt.Dimension(40, 16));
        setembro.setName("9"); // NOI18N
        setembro.setOpaque(true);
        setembro.setPreferredSize(new java.awt.Dimension(40, 16));
        add(setembro);

        outubro.setForeground(new java.awt.Color(75, 75, 75));
        outubro.setText("Outubro");
        outubro.setMaximumSize(new java.awt.Dimension(40, 16));
        outubro.setMinimumSize(new java.awt.Dimension(40, 16));
        outubro.setName("10"); // NOI18N
        outubro.setOpaque(true);
        outubro.setPreferredSize(new java.awt.Dimension(40, 16));
        add(outubro);

        novembro.setForeground(new java.awt.Color(75, 75, 75));
        novembro.setText("Novembro");
        novembro.setMaximumSize(new java.awt.Dimension(40, 16));
        novembro.setMinimumSize(new java.awt.Dimension(40, 16));
        novembro.setName("11"); // NOI18N
        novembro.setOpaque(true);
        novembro.setPreferredSize(new java.awt.Dimension(40, 16));
        add(novembro);

        dezembro.setForeground(new java.awt.Color(75, 75, 75));
        dezembro.setText("Dezembro");
        dezembro.setMaximumSize(new java.awt.Dimension(40, 16));
        dezembro.setMinimumSize(new java.awt.Dimension(40, 16));
        dezembro.setName("12"); // NOI18N
        dezembro.setOpaque(true);
        dezembro.setPreferredSize(new java.awt.Dimension(40, 16));
        add(dezembro);
    }// </editor-fold>//GEN-END:initComponents

    public Evento getEvento() {
        return evento;
    }

    public void setEvento(Evento evento) {
        this.evento = evento;
        addEvento();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private SuperSwing.Componente.DatePicker.Botao abril;
    private SuperSwing.Componente.DatePicker.Botao agosto;
    private SuperSwing.Componente.DatePicker.Botao dezembro;
    private SuperSwing.Componente.DatePicker.Botao fevereiro;
    private SuperSwing.Componente.DatePicker.Botao janeiro;
    private SuperSwing.Componente.DatePicker.Botao julho;
    private SuperSwing.Componente.DatePicker.Botao junho;
    private SuperSwing.Componente.DatePicker.Botao maio;
    private SuperSwing.Componente.DatePicker.Botao marco;
    private SuperSwing.Componente.DatePicker.Botao novembro;
    private SuperSwing.Componente.DatePicker.Botao outubro;
    private SuperSwing.Componente.DatePicker.Botao setembro;
    // End of variables declaration//GEN-END:variables
}
